### ISSUE TITLE
StorageAccount class not found

### ISSUE THREAD

**Issue by mkostin** [MSOpenTech/msopentech-tools-for-intellij#131]
Hi thanks a lot for the plugin!

I've got the following error. No clear repro steps unfortunately:
 - Just started IDEA
 - Was NOT using plugin functionality
 - Got error after ~3-5 minutes

```
Error: com.microsoftopentechnologies.storageregistry.StorageAccount PluginClassLoader[com.microsoftopentechnologies.intellij, 0.1.74]
java.lang.ClassNotFoundException: com.microsoftopentechnologies.storageregistry.StorageAccount PluginClassLoader[com.microsoftopentechnologies.intellij, 0.1.74]
	at com.intellij.ide.plugins.cl.PluginClassLoader.loadClass(PluginClassLoader.java:68)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:344)
	at java.io.ObjectInputStream.resolveClass(ObjectInputStream.java:626)
	at java.io.ObjectInputStream.readNonProxyDesc(ObjectInputStream.java:1613)
	at java.io.ObjectInputStream.readClassDesc(ObjectInputStream.java:1518)
	at java.io.ObjectInputStream.readArray(ObjectInputStream.java:1664)
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1345)
	at java.io.ObjectInputStream.readObject(ObjectInputStream.java:371)
	at com.microsoftopentechnologies.intellij.AzureSettings.loadStorage(AzureSettings.java:70)
	at com.microsoftopentechnologies.intellij.AzurePlugin.initComponent(AzurePlugin.java:82)
	at com.intellij.openapi.components.impl.ComponentManagerImpl$ComponentConfigComponentAdapter$1.getComponentInstance(ComponentManagerImpl.java:567)
	at com.intellij.openapi.components.impl.ComponentManagerImpl$ComponentConfigComponentAdapter.getComponentInstance(ComponentManagerImpl.java:609)
	at com.intellij.util.pico.DefaultPicoContainer.getLocalInstance(DefaultPicoContainer.java:236)
	at com.intellij.util.pico.DefaultPicoContainer.getInstance(DefaultPicoContainer.java:223)
	at com.intellij.util.pico.DefaultPicoContainer.getComponentInstance(DefaultPicoContainer.java:210)
	at org.picocontainer.alternatives.AbstractDelegatingMutablePicoContainer.getComponentInstance(AbstractDelegatingMutablePicoContainer.java:75)
	at com.intellij.openapi.components.impl.ComponentManagerImpl.createComponent(ComponentManagerImpl.java:124)
	at com.intellij.openapi.components.impl.ComponentManagerImpl.a(ComponentManagerImpl.java:115)
	at com.intellij.openapi.components.impl.ComponentManagerImpl.init(ComponentManagerImpl.java:86)
	at com.intellij.openapi.project.impl.ProjectImpl.init(ProjectImpl.java:297)
	at com.intellij.openapi.project.impl.ProjectManagerImpl.a(ProjectManagerImpl.java:300)
	at com.intellij.openapi.project.impl.ProjectManagerImpl.access$700(ProjectManagerImpl.java:86)
	at com.intellij.openapi.project.impl.ProjectManagerImpl$12.compute(ProjectManagerImpl.java:611)
	at com.intellij.openapi.project.impl.ProjectManagerImpl$12.compute(ProjectManagerImpl.java:607)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl$5.run(ProgressManagerImpl.java:381)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl$TaskRunnable.run(ProgressManagerImpl.java:621)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl$7.run(ProgressManagerImpl.java:422)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl$3.run(ProgressManagerImpl.java:194)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.a(ProgressManagerImpl.java:281)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:233)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.runProcess(ProgressManagerImpl.java:181)
	at com.intellij.openapi.application.impl.ApplicationImpl$10$1.run(ApplicationImpl.java:641)
	at com.intellij.openapi.application.impl.ApplicationImpl$8.run(ApplicationImpl.java:406)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
	at org.jetbrains.ide.PooledThreadExecutor$1$1.run(PooledThreadExecutor.java:56)
```

**Comment by BeatriceOltean** [comment]
This may be related to the Azure plugin component. To talk to Elena

**Comment by babumuralidharan** [comment]
This error is not reproducable anymore with the latest code. Feel free to open if you repro this issue.
