### ISSUE TITLE
Exception after finishing to create a new storage account 

### ISSUE THREAD

**Issue by BeatriceOltean** [MSOpenTech/msopentech-tools-for-intellij#155]
com.microsoft.azure.storage.StorageException: Empty key
	at com.microsoft.azure.storage.core.ExecutionEngine.setupStorageRequest(ExecutionEngine.java:407)
	at com.microsoft.azure.storage.core.ExecutionEngine.executeWithRetry(ExecutionEngine.java:102)
	at com.microsoft.azure.storage.blob.CloudBlobContainer.exists(CloudBlobContainer.java:749)
	at com.microsoft.azure.storage.blob.CloudBlobContainer.createIfNotExists(CloudBlobContainer.java:360)
	at com.microsoft.azure.storage.blob.CloudBlobContainer.createIfNotExists(CloudBlobContainer.java:336)
	at com.microsoftopentechnologies.intellij.helpers.azure.sdk.AzureSDKManagerImpl.getMediaLocation(AzureSDKManagerImpl.java:1095)
	at com.microsoftopentechnologies.intellij.helpers.azure.sdk.AzureSDKManagerImpl.createVirtualMachine(AzureSDKManagerImpl.java:585)
	at com.microsoftopentechnologies.intellij.helpers.azure.sdk.AzureSDKManagerADAuthDecorator$16.run(AzureSDKManagerADAuthDecorator.java:275)
	at com.microsoftopentechnologies.intellij.helpers.azure.sdk.AzureSDKManagerADAuthDecorator$16.run(AzureSDKManagerADAuthDecorator.java:272)
	at com.microsoftopentechnologies.intellij.helpers.azure.sdk.AzureSDKManagerADAuthDecorator.runWithRetry(AzureSDKManagerADAuthDecorator.java:47)
	at com.microsoftopentechnologies.intellij.helpers.azure.sdk.AzureSDKManagerADAuthDecorator.createVirtualMachine(AzureSDKManagerADAuthDecorator.java:272)
	at com.microsoftopentechnologies.intellij.wizards.createvm.EndpointStep$4.run(EndpointStep.java:191)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl$TaskRunnable.run(ProgressManagerImpl.java:621)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl$3.run(ProgressManagerImpl.java:194)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.registerIndicatorAndRun(ProgressManagerImpl.java:281)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:233)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.runProcess(ProgressManagerImpl.java:181)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl$9.run(ProgressManagerImpl.java:530)
	at com.intellij.openapi.application.impl.ApplicationImpl$8.run(ApplicationImpl.java:406)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
	at org.jetbrains.ide.PooledThreadExecutor$1$1.run(PooledThreadExecutor.java:56)
Caused by: java.lang.IllegalArgumentException: Empty key
	at javax.crypto.spec.SecretKeySpec.<init>(SecretKeySpec.java:94)
	at com.microsoft.azure.storage.StorageKey.initHmacSha256(StorageKey.java:156)
	at com.microsoft.azure.storage.StorageKey.computeMacSha256(StorageKey.java:49)
	at com.microsoft.azure.storage.core.BaseRequest.signRequestForBlobAndQueue(BaseRequest.java:438)
	at com.microsoft.azure.storage.core.StorageCredentialsHelper.signBlobAndQueueRequest(StorageCredentialsHelper.java:149)
	at com.microsoft.azure.storage.core.StorageRequest.signBlobQueueAndFileRequest(StorageRequest.java:312)
	at com.microsoft.azure.storage.blob.CloudBlobContainer$5.signRequest(CloudBlobContainer.java:775)
	at com.microsoft.azure.storage.blob.CloudBlobContainer$5.signRequest(CloudBlobContainer.java:756)
	at com.microsoft.azure.storage.core.ExecutionEngine.setupStorageRequest(ExecutionEngine.java:396)
	... 24 more

**Comment by kasturiswain** [comment]
This issue is fixed and functionality is working as expected in the latest build.
