### ISSUE TITLE
Error creating VM images: A security token validation error occured for the received JWT token

### ISSUE THREAD

**Issue by BeatriceOltean** [MSOpenTech/msopentech-tools-for-intellij#185]
Steps:
1. install the 2/29 build from Team City 
2. Select Server Explorer Virtual Machines
3. In the VM Image wizard sign in with MS Account and select a subscription 
4. Error creating VM images 

java.util.concurrent.ExecutionException: com.microsoft.windowsazure.exception.ServiceException: AuthenticationFailed: A security token validation error occured for the received JWT token.
	at com.google.common.util.concurrent.AbstractFuture$Sync.getValue(AbstractFuture.java:299)
	at com.google.common.util.concurrent.AbstractFuture$Sync.get(AbstractFuture.java:286)
	at com.google.common.util.concurrent.AbstractFuture.get(AbstractFuture.java:116)
	at com.microsoftopentechnologies.intellij.helpers.azure.sdk.AzureSDKManagerImpl.getVirtualMachineImages(AzureSDKManagerImpl.java:450)
	at com.microsoftopentechnologies.intellij.helpers.azure.sdk.AzureSDKManagerADAuthDecorator$10.run(AzureSDKManagerADAuthDecorator.java:205)
	at com.microsoftopentechnologies.intellij.helpers.azure.sdk.AzureSDKManagerADAuthDecorator$10.run(AzureSDKManagerADAuthDecorator.java:202)
	at com.microsoftopentechnologies.intellij.helpers.azure.sdk.AzureSDKManagerADAuthDecorator.runWithRetry(AzureSDKManagerADAuthDecorator.java:47)
	at com.microsoftopentechnologies.intellij.helpers.azure.sdk.AzureSDKManagerADAuthDecorator.getVirtualMachineImages(AzureSDKManagerADAuthDecorator.java:202)
	at com.microsoftopentechnologies.intellij.wizards.createvm.SelectImageStep$8.run(SelectImageStep.java:247)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl$TaskRunnable.run(ProgressManagerImpl.java:621)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl$3.run(ProgressManagerImpl.java:194)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.registerIndicatorAndRun(ProgressManagerImpl.java:281)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:233)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.runProcess(ProgressManagerImpl.java:181)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl$9.run(ProgressManagerImpl.java:530)
	at com.intellij.openapi.application.impl.ApplicationImpl$8.run(ApplicationImpl.java:406)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
	at org.jetbrains.ide.PooledThreadExecutor$1$1.run(PooledThreadExecutor.java:56)
Caused by: com.microsoft.windowsazure.exception.ServiceException: AuthenticationFailed: A security token validation error occured for the received JWT token.
	at com.microsoft.windowsazure.exception.ServiceException.createFromXml(ServiceException.java:216)
	at com.microsoft.windowsazure.management.compute.VirtualMachineOSImageOperationsImpl.list(VirtualMachineOSImageOperationsImpl.java:1501)
	at com.microsoftopentechnologies.intellij.helpers.azure.sdk.AzureSDKManagerImpl.getOSImages(AzureSDKManagerImpl.java:1224)
	at com.microsoftopentechnologies.intellij.helpers.azure.sdk.AzureSDKManagerImpl.access$200(AzureSDKManagerImpl.java:62)
	at com.microsoftopentechnologies.intellij.helpers.azure.sdk.AzureSDKManagerImpl$3.run(AzureSDKManagerImpl.java:1209)
	... 7 more

**Comment by leotilli** [comment]
I've tested it but I cannot reproduce it.

I've tried clearing cache from the default browser, and after providing the security credentials I've tried with leaving the option of 'keep me signed in' unchecked and checked.

**Comment by BeatriceOltean** [comment]
You have to be logged when you update the plugin to repro this issue.

**Comment by avranju** [comment]
Is this a fresh sign-in? If not, this might be the same problem as issue #57.

**Comment by BeatriceOltean** [comment]
It is not a fresh sign-in. Let's close both when we have the fix.

**Comment by kasturiswain** [comment]
This issue is fixed and functionality is working as expected in the latest build.
