### ISSUE TITLE
AD signin broken in Mac- User account identifier not provided error

### ISSUE THREAD

**Issue by babumuralidharan** [MSOpenTech/msopentech-tools-for-intellij#255]
AD signin seems to be broken in Mac. After signin and trying to load mobileservices/virtual machines we get the following error. 

![image](https://cloud.githubusercontent.com/assets/1501823/6976812/f668a334-d963-11e4-861b-050865861580.png)

**Errorlog**:

```
java.lang.UnsupportedOperationException: An error occurred while acquiring an access token.
    at com.microsoftopentechnologies.intellij.helpers.azure.sdk.AuthTokenRequestFilter.filter(AuthTokenRequestFilter.java:49)
    at com.microsoft.windowsazure.core.pipeline.apache.HttpRequestInterceptorAdapter.process(HttpRequestInterceptorAdapter.java:42)
    at org.apache.http.protocol.ImmutableHttpProcessor.process(ImmutableHttpProcessor.java:131)
    at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:192)
    at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:85)
    at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:108)
    at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:186)
    at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:82)
    at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:106)
    at com.microsoft.windowsazure.management.compute.HostedServiceOperationsImpl.list(HostedServiceOperationsImpl.java:3687)
    at com.microsoftopentechnologies.intellij.helpers.azure.sdk.AzureSDKManagerImpl.getHostedServices(AzureSDKManagerImpl.java:1331)
    at com.microsoftopentechnologies.intellij.helpers.azure.sdk.AzureSDKManagerImpl.getVirtualMachines(AzureSDKManagerImpl.java:195)
    at com.microsoftopentechnologies.intellij.helpers.azure.sdk.AzureSDKManagerADAuthDecorator$2.run(AzureSDKManagerADAuthDecorator.java:131)
    at com.microsoftopentechnologies.intellij.helpers.azure.sdk.AzureSDKManagerADAuthDecorator$2.run(AzureSDKManagerADAuthDecorator.java:128)
    at com.microsoftopentechnologies.intellij.helpers.azure.sdk.AzureSDKManagerADAuthDecorator.runWithRetry(AzureSDKManagerADAuthDecorator.java:51)
    at com.microsoftopentechnologies.intellij.helpers.azure.sdk.AzureSDKManagerADAuthDecorator.getVirtualMachines(AzureSDKManagerADAuthDecorator.java:128)
    at com.microsoftopentechnologies.intellij.serviceexplorer.azure.vm.VMServiceModule.refreshItems(VMServiceModule.java:52)
    at com.microsoftopentechnologies.intellij.serviceexplorer.Node.refreshItems(Node.java:334)
    at com.microsoftopentechnologies.intellij.serviceexplorer.Node$BackgroundLoader.run(Node.java:424)
    at com.intellij.openapi.progress.impl.ProgressManagerImpl$TaskRunnable.run(ProgressManagerImpl.java:471)
    at com.intellij.openapi.progress.impl.ProgressManagerImpl$2.run(ProgressManagerImpl.java:178)
    at com.intellij.openapi.progress.ProgressManager.executeProcessUnderProgress(ProgressManager.java:209)
    at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:212)
    at com.intellij.openapi.progress.impl.ProgressManagerImpl.runProcess(ProgressManagerImpl.java:171)
    at com.intellij.openapi.progress.impl.ProgressManagerImpl$8.run(ProgressManagerImpl.java:380)
    at com.intellij.openapi.application.impl.ApplicationImpl$8.run(ApplicationImpl.java:419)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:439)
    at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:303)
    at java.util.concurrent.FutureTask.run(FutureTask.java:138)
    at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:895)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:918)
    at java.lang.Thread.run(Thread.java:695)
    at com.intellij.openapi.application.impl.ApplicationImpl$1$1.run(ApplicationImpl.java:149)
Caused by: java.util.concurrent.ExecutionException: java.lang.IllegalArgumentException: An error occurred during authentication. 'code' is null/empty.
Error code: login_required
Description: AADSTS50058: User account identifier is not provided.
Trace ID: 2923be1e-b7bf-4da4-8982-689116d1e082
Correlation ID: 9757f85c-400b-4933-91d5-21509fe961e5
Timestamp: 2015-04-03 00:59:01Z
    at com.google.common.util.concurrent.AbstractFuture$Sync.getValue(AbstractFuture.java:299)
    at com.google.common.util.concurrent.AbstractFuture$Sync.get(AbstractFuture.java:286)
    at com.google.common.util.concurrent.AbstractFuture.get(AbstractFuture.java:116)
    at com.microsoftopentechnologies.intellij.helpers.azure.rest.AzureRestAPIHelper.acquireTokenInteractive(AzureRestAPIHelper.java:472)
    at com.microsoftopentechnologies.intellij.helpers.azure.sdk.AuthTokenRequestFilter.filter(AuthTokenRequestFilter.java:47)
    ... 32 more
Caused by: java.lang.IllegalArgumentException: An error occurred during authentication. 'code' is null/empty.
Error code: login_required
Description: AADSTS50058: User account identifier is not provided.
Trace ID: 2923be1e-b7bf-4da4-8982-689116d1e082
Correlation ID: 9757f85c-400b-4933-91d5-21509fe961e5
Timestamp: 2015-04-03 00:59:01Z
    at com.microsoftopentechnologies.intellij.helpers.aadauth.AuthenticationContext$2.onAuthCodeReceived(AuthenticationContext.java:346)
    at com.microsoftopentechnologies.intellij.helpers.webserver.AADWebServer$AuthRequestHandler.handle(AADWebServer.java:79)
    at com.microsoftopentechnologies.intellij.helpers.webserver.WebServer$1.handle(WebServer.java:82)
    at com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:65)
    at sun.net.httpserver.AuthFilter.doFilter(AuthFilter.java:65)
    at com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:68)
    at sun.net.httpserver.ServerImpl$Exchange$LinkHandler.handle(ServerImpl.java:566)
    at com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:65)
    at sun.net.httpserver.ServerImpl$Exchange.run(ServerImpl.java:538)
    at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:895)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:918)
    at java.lang.Thread.run(Thread.java:695)

```

**Comment by BeatriceOltean** [comment]
Omindra, I am not able to reproduce this one on Win. Please validate.

**Comment by omendrapandey** [comment]
@BeatriceOltean , the AD sign in is working fine on Windows OS.
Adding @babumuralidharan  to verify this for Mac OS .
