### ISSUE TITLE
No Class deffound error when adding O365 activity

### ISSUE THREAD

**Issue by babumuralidharan** [MSOpenTech/msopentech-tools-for-intellij#276]
Create an application.
Create a new O365 activity.
Do a sign in.
In my case my login do not return any token from AD. It just shows status as loading in O365 screen and i get no class deffound error.
To repro you can either enter wrong credentials or just cancel the activity you should be able to see this error.

**_Error log:**_

```

java.lang.NoClassDefFoundError: com/microsoftopentechnologies/intellij/helpers/graph/PluginDependencyResolver
    at com.microsoftopentechnologies.intellij.helpers.o365.Office365RestAPIManager.getDirectoryClient(Office365RestAPIManager.java:184)
    at com.microsoftopentechnologies.intellij.helpers.o365.Office365RestAPIManager.access$300(Office365RestAPIManager.java:55)
    at com.microsoftopentechnologies.intellij.helpers.o365.Office365RestAPIManager$4.execute(Office365RestAPIManager.java:338)
    at com.microsoftopentechnologies.intellij.helpers.o365.Office365RestAPIManager.requestWithToken(Office365RestAPIManager.java:305)
    at com.microsoftopentechnologies.intellij.helpers.o365.Office365RestAPIManager.getApplicationList(Office365RestAPIManager.java:335)
    at com.microsoftopentechnologies.intellij.wizards.activityConfiguration.Office365Step.fillApps(Office365Step.java:364)
    at com.microsoftopentechnologies.intellij.wizards.activityConfiguration.Office365Step.access$900(Office365Step.java:54)
    at com.microsoftopentechnologies.intellij.wizards.activityConfiguration.Office365Step$4.run(Office365Step.java:302)
    at com.intellij.openapi.application.impl.ApplicationImpl$8.run(ApplicationImpl.java:405)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
    at java.util.concurrent.FutureTask.run(FutureTask.java:262)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
    at java.lang.Thread.run(Thread.java:745)
    at org.jetbrains.ide.PooledThreadExecutor$1$1.run(PooledThreadExecutor.java:56)


```

**Comment by babumuralidharan** [comment]
This is working fine with the latest source .Now we do not see this error anymore
