### ISSUE TITLE
Plugin failed to initialize and is disabled 

### ISSUE THREAD

**Issue by omendrapandey** [MSOpenTech/msopentech-tools-for-intellij#312]
OS - Windows , Ubuntu 14.04
<b>Plugin Version - 0.1.211</b>
IDE -Intellij 14.1.3 ,  Android Studio 1.2.1.1 , JRE 1.8

Steps -
Installed MS open tech plugin in the IDE .
Restarted the IDE .
A dialog box "Plugin Error " pops up while restarting the IDE .
![untitled](https://cloud.githubusercontent.com/assets/12275872/7806388/c610c6f8-039d-11e5-9897-4f85e1f6e24d.png)
Error log 
<pre><code>Plugin 'com.microsoftopentechnologies.intellij' failed to initialize and will be disabled.  Please restart IntelliJ IDEA.

java.lang.NoClassDefFoundError: com/microsoftopentechnologies/tooling/msservices/serviceexplorer/azure/storage/ExternalStorageNode
    at com.microsoftopentechnologies.intellij.serviceexplorer.NodeActionsMap.<clinit>(NodeActionsMap.java:52)
    at com.microsoftopentechnologies.intellij.components.MSOpenTechToolsApplication.initComponent(MSOpenTechToolsApplication.java:88)
    at com.intellij.openapi.components.impl.ComponentManagerImpl$ComponentConfigComponentAdapter$1.getComponentInstance(ComponentManagerImpl.java:568)
    at com.intellij.openapi.components.impl.ComponentManagerImpl$ComponentConfigComponentAdapter.getComponentInstance(ComponentManagerImpl.java:610)
    at com.intellij.util.pico.DefaultPicoContainer.getLocalInstance(DefaultPicoContainer.java:245)
    at com.intellij.util.pico.DefaultPicoContainer.getComponentInstance(DefaultPicoContainer.java:211)
    at com.intellij.openapi.components.impl.ComponentManagerImpl.createComponent(ComponentManagerImpl.java:125)
    at com.intellij.openapi.application.impl.ApplicationImpl.createComponent(ApplicationImpl.java:354)
    at com.intellij.openapi.components.impl.ComponentManagerImpl.createComponents(ComponentManagerImpl.java:116)
    at com.intellij.openapi.components.impl.ComponentManagerImpl.init(ComponentManagerImpl.java:87)
    at com.intellij.openapi.components.impl.stores.ApplicationStoreImpl.load(ApplicationStoreImpl.java:101)
    at com.intellij.openapi.application.impl.ApplicationImpl.load(ApplicationImpl.java:499)
    at com.intellij.openapi.application.impl.ApplicationImpl.load(ApplicationImpl.java:481)
    at com.intellij.idea.IdeaApplication.run(IdeaApplication.java:170)
    at com.intellij.idea.MainImpl$1$1$1.run(MainImpl.java:52)
    at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
    at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:749)
    at java.awt.EventQueue.access$500(EventQueue.java:97)
    at java.awt.EventQueue$3.run(EventQueue.java:702)
    at java.awt.EventQueue$3.run(EventQueue.java:696)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:75)
    at java.awt.EventQueue.dispatchEvent(EventQueue.java:719)
    at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:362)
    at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
    at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
    at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
    at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
Caused by: java.lang.ClassNotFoundException: com.microsoftopentechnologies.tooling.msservices.serviceexplorer.azure.storage.ExternalStorageNode PluginClassLoader[com.microsoftopentechnologies.intellij, 0.1.211]
    at com.intellij.ide.plugins.cl.PluginClassLoader.loadClass(PluginClassLoader.java:68)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
    ... 30 more
</pre></code>

**Comment by omendrapandey** [comment]
Issue not reproducible in<b> Plugin version 0.1.212 </b>, Closing it .
