### ISSUE TITLE
Vm creation throwing error while using newly created cloud services

### ISSUE THREAD

**Issue by omendrapandey** [MSOpenTech/msopentech-tools-for-intellij#319]
<b>Environment</b>
OS - Windows
Plugin Version - 0.1.216
IDE - Intellij Idea Ultimate 14.1.3 , JRE 1.8
Authentication - Publish Settings file

<b>Steps</b>
Expand Azure.
Right Click Virtual Machines.
Select Create VM.
Choose the Subscription and Click Next.
Choose the Image and Click Next.
Fill the Machine settings by giving VM name , Size and Password , Then Click Next.
<b>Create a new Cloud Service and new Storage Account , Then Click Next.
Select default endpoints , Then  Click Finish.
It pops up a error dialog box as attached below .</b>
![untitled](https://cloud.githubusercontent.com/assets/12275872/7881182/da067efa-061d-11e5-9454-8ea140c711e7.png)

<b>Error Log -

<pre><code>java.lang.IllegalArgumentException: Invalid connection string.
    at com.microsoft.azure.storage.CloudStorageAccount.parse(CloudStorageAccount.java:248)
    at com.microsoftopentechnologies.tooling.msservices.helpers.azure.sdk.AzureSDKHelper.getCloudStorageAccount(AzureSDKHelper.java:146)
    at com.microsoftopentechnologies.tooling.msservices.helpers.azure.sdk.AzureSDKManagerImpl.getCloudBlobClient(AzureSDKManagerImpl.java:866)
    at com.microsoftopentechnologies.tooling.msservices.helpers.azure.sdk.AzureSDKManagerImpl.getMediaLocation(AzureSDKManagerImpl.java:1425)
    at com.microsoftopentechnologies.tooling.msservices.helpers.azure.sdk.AzureSDKManagerImpl.createVirtualMachine(AzureSDKManagerImpl.java:670)
    at com.microsoftopentechnologies.intellij.wizards.createvm.EndpointStep$4.run(EndpointStep.java:242)
    at com.intellij.openapi.progress.impl.CoreProgressManager$TaskRunnable.run(CoreProgressManager.java:563)
    at com.intellij.openapi.progress.impl.CoreProgressManager$2.run(CoreProgressManager.java:152)
    at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:452)
    at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:402)
    at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:54)
    at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:137)
    at com.intellij.openapi.progress.impl.ProgressManagerImpl$1.run(ProgressManagerImpl.java:126)
    at com.intellij.openapi.application.impl.ApplicationImpl$8.run(ApplicationImpl.java:400)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)
    at org.jetbrains.ide.PooledThreadExecutor$1$1.run(PooledThreadExecutor.java:56)
</code></pre>

<b>Note - VM will create successfully for the second time if we select just now created Cloud service and storage account instead of creating new cloud service and Storage account.</b>

**Comment by omendrapandey** [comment]
This issue is fixed now .
