### ISSUE TITLE
intellij 15.0.1 Mac 10.11.1 Plugin 'com.microsoftopentechnologies.intellij' failed to initialize and will be disabled.

### ISSUE THREAD

**Issue by keepscoding** [MSOpenTech/msopentech-tools-for-intellij#381]
I got this error when restart intellij after installation this plugin.

Plugin 'com.microsoftopentechnologies.intellij' failed to initialize and will be disabled.  Please restart IntelliJ IDEA.

java.lang.NoClassDefFoundError: com/intellij/util/PlatformUtilsCore
    at com.microsoftopentechnologies.intellij.AzurePlugin.<clinit>(AzurePlugin.java:52)
    at java.lang.Class.forName0(Native Method)
    at java.lang.Class.forName(Class.java:348)
    at com.intellij.openapi.components.impl.ComponentManagerImpl.a(ComponentManagerImpl.java:408)
    at com.intellij.openapi.components.impl.ComponentManagerImpl.init(ComponentManagerImpl.java:96)
    at com.intellij.openapi.components.impl.ComponentManagerImpl.init(ComponentManagerImpl.java:90)
    at com.intellij.openapi.project.impl.ProjectImpl.init(ProjectImpl.java:299)
    at com.intellij.openapi.project.impl.ProjectManagerImpl.a(ProjectManagerImpl.java:228)
    at com.intellij.openapi.project.impl.ProjectManagerImpl.access$300(ProjectManagerImpl.java:66)
    at com.intellij.openapi.project.impl.ProjectManagerImpl$3.run(ProjectManagerImpl.java:308)
    at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:446)
    at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:392)
    at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:54)
    at com.intellij.openapi.progress.impl.CoreProgressManager.executeNonCancelableSection(CoreProgressManager.java:170)
    at com.intellij.openapi.project.impl.ProjectManagerImpl.getDefaultProject(ProjectManagerImpl.java:303)
    at com.intellij.ide.fileTemplates.FileTemplateManager.getDefaultInstance(FileTemplateManager.java:67)
    at com.intellij.ide.fileTemplates.FileTemplateManager.getInstance(FileTemplateManager.java:63)
    at com.dci.intellij.dbn.DatabaseNavigator.initComponent(DatabaseNavigator.java:60)
    at com.intellij.openapi.components.impl.ComponentManagerImpl$ComponentConfigComponentAdapter.getComponentInstance(ComponentManagerImpl.java:518)
    at com.intellij.openapi.components.impl.ComponentManagerImpl.createComponents(ComponentManagerImpl.java:123)
    at com.intellij.openapi.application.impl.ApplicationImpl.access$801(ApplicationImpl.java:90)
    at com.intellij.openapi.application.impl.ApplicationImpl$12.run(ApplicationImpl.java:496)
    at com.intellij.openapi.progress.impl.CoreProgressManager$2.run(CoreProgressManager.java:142)
    at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:446)
    at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:392)
    at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:54)
    at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:127)
    at com.intellij.openapi.application.impl.ApplicationImpl.createComponents(ApplicationImpl.java:505)
    at com.intellij.openapi.components.impl.ComponentManagerImpl.init(ComponentManagerImpl.java:107)
    at com.intellij.openapi.application.impl.ApplicationImpl.load(ApplicationImpl.java:454)
    at com.intellij.openapi.application.impl.ApplicationImpl.load(ApplicationImpl.java:446)
    at com.intellij.idea.IdeaApplication.run(IdeaApplication.java:194)
    at com.intellij.idea.MainImpl$1$1$1.run(MainImpl.java:63)
    at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
    at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:749)
    at java.awt.EventQueue.access$500(EventQueue.java:97)
    at java.awt.EventQueue$3.run(EventQueue.java:702)
    at java.awt.EventQueue$3.run(EventQueue.java:696)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:75)
    at java.awt.EventQueue.dispatchEvent(EventQueue.java:719)
    at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:360)
    at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
    at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
    at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
    at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
Caused by: java.lang.ClassNotFoundException: com.intellij.util.PlatformUtilsCore PluginClassLoader[com.microsoftopentechnologies.intellij, 0.1.255]
    at com.intellij.ide.plugins.cl.PluginClassLoader.loadClass(PluginClassLoader.java:68)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
    ... 48 more

**Comment by lenala** [comment]
The plugin you are looking at is now being split into 3 separate plugins, one for Java developers on Azure, one for Android developers, and one which is a common dependency of the other two, which includes the Azure services explorer. They all work in IntelliJ 15. The Azure Toolkit for Java plugin and the Azure Services Explorer plugin are already available:
-          https://plugins.jetbrains.com/plugin/8053
-          https://plugins.jetbrains.com/plugin/8052
  We expect the one for Android (if that’s what you’re looking for) to be released over the next few days. It will also support the latest intelliJ 15.

**Comment by keepscoding** [comment]
so, ms one tech is no longer in use?

**Comment by lenala** [comment]
The 3 new plugins are the new version of this single msopentech plugin. We 've split its functionality among those 3. So the msopentech one will no longer be worked on because the 3 new plugins are taking its place. Besides containing all of the msopentech plugin's functionality, they also have some additional enhancements. 
Btw, we've now also released the Android plugin, containing the Android-specific parts of the msopentech plugin's functionality: http://plugins.jetbrains.com/plugin/8077?pr.

**Comment by keepscoding** [comment]
Thanks. then, it will be better if ms can remove the obsolete plugin from intelliJ plugin repo
